Zoro.Web/Areas/Customer/Controllers/UserOrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages;
using Zoro.Application.ApplicationConstants;
using Zoro.Application.Contracts.Persistence;
using Zoro.Domain.Models;
using Zoro.Domain.ViewModel;
using Zoro.Infrastructure.Migrations;

namespace Zoro.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
    [Authorize(Roles = CustomRole.Customer)]
    public class UserOrdersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<IdentityUser> _userManager;

        public UserOrdersController(IUnitOfWork unitOfWork, UserManager<IdentityUser> userManager)
        {

            _unitOfWork = unitOfWork;
            _userManager = userManager;
           
        }



        [HttpGet]
        [Authorize]
        public async Task <IActionResult> Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }

            var userId = _userManager.GetUserId(User);

            if (userId == null)
            {
                return RedirectToAction("Login", "Account", new { area = "" });
            }


            var orderProducts = await _unitOfWork.OrderProducts.GetByUserIdAsync(userId);

            var viewModel = orderProducts.Select(cp => new OrderProductsVm
            {
                UserID = userId,
                Id = cp.Id.ToString(),
                ProductId = cp.ProductId,
                ProductName = cp.ProductName,
                Price = cp.Price,
                Quantity = cp.Quantity,
                CreateOn = cp.CreateOn,
                UserAddress=cp.UserAddress,
                phoneNumber=cp.PhoneNumber,
                OrderStatus=cp.OrderStatus,
                TotalPrice=cp.TotalPrice,
                Image = cp.Image

            }).ToList();

            return View(viewModel);

           
        }


        public async Task<IActionResult> Deleteorderproduct(string Id)
        {

            var userId = _userManager.GetUserId(User);
            try
            {
                var orderProducts = await _unitOfWork.OrderProducts.GeTByIDAsync(userId, Id);
                if (orderProducts != null)
                {
                    await _unitOfWork.OrderProducts.Delete(orderProducts);
                    await _unitOfWork.SaveAsync();
                    TempData["SuccessMessage"] = "Item deleted successfully!";
                }
                else
                {
                    TempData["ErrorMessage"] = "Item not found!";
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = $"An error occurred: {ex.Message}";
            }
            return RedirectToAction(nameof(Index));

             
        }

        [HttpGet]
        public async Task<IActionResult> UserOrderHistory()
        {
            var userId = _userManager.GetUserId(User);

            var CompletedOrder = await _unitOfWork.CompletedOrders.GetAllCartByIdAsync(userId);

            var viewModel = CompletedOrder.Select(cp => new CompletedOrderVM
            {
               
                UserID = userId,
                UserName= cp.UserName,
                OrderId=cp.OrderId,
                Id = cp.Id.ToString(),
                ProductId = cp.ProductId,
                ProductName = cp.ProductName,
                Price = cp.Price,
                Quantity = cp.Quantity,
                CreateOn = cp.CreateOn,            
                PhoneNumber = cp.PhoneNumber,
                OrderStatus = cp.OrderStatus,
                TotalPrice = cp.TotalPrice,
                ModifiedOn= cp.ModifiedOn,
                Image = cp.Image

            }).ToList();

            return View(viewModel);




        }



    }
}

Zoro.Web/Areas/Customer/Views/UserOrders/Index.cshtml
@model List<Zoro.Domain.ViewModel.OrderProductsVm>

<div class="container">
    <div class="row mb-4">
        <div class="col-md-6 text-uppercase">
            <h3>
               Your Orders

            </h3>
        </div>

        <div class="col-md-6 text-end">
            <a asp-area="Customer" asp-controller="UserOrders" asp-action="UserOrderHistory" class="btn btn-primary"><i class="bi bi-card-list">Order History</i></a>
        </div>


    </div>

</div>



<br />
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">
        @TempData["ErrorMessage"]
    </div>
}


@if (Model == null || !Model.Any())
{
   <center><h3>No products in your Order.</h3></center>
    <center><img src="~/images/logo/oip.jpeg" /></center>
  
}
else
{
    <div class="table-responsive">
<table class="table table-bordered table-striped table-responsive-lg text-xxl-center text-center" id="tablee">
    <thead>
        <tr>
            <th>order Date&Time</th>
            <th>Product Name</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Total Price</th>
            <th>Order Status</th>
            <th>phone Number</th>
            <th>Address</th>
            <th></th>
            <th>Cancel Order</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var orderProduct in Model)
        {
            
            
                <tr>
                <td>@orderProduct.CreateOn</td>
                    <td>@orderProduct.ProductName</td>
                <td>@orderProduct.Quantity</td>
                <td>@orderProduct.Price.ToString("C")</td>
                <td>@orderProduct.TotalPrice.ToString("C")</td>

                    @if (@orderProduct.OrderStatus=="Pending")
                    {
                        <td><button class="btn btn-info btn-lg btn-block ">@orderProduct.OrderStatus.ToString()</button></td>
                    }
                    else if(@orderProduct.OrderStatus=="Ready_To_Pickup")
                    {
                        <td><button class="btn btn-success btn-lg btn-block">@orderProduct.OrderStatus.ToString()</button></td>

                    }

                    
                <td>@orderProduct.phoneNumber.ToString()</td>
               
                <td>@orderProduct.UserAddress.ToString()</td>
                <td> <img src="@orderProduct.Image" class="img-fluid" style="max-width: 100px; max-height: 100px;"></td>
                <td>
                    <form asp-area="Customer" asp-controller="UserOrders" asp-action="Deleteorderproduct" method="post">
                        <input type="hidden" name="Id" value="@orderProduct.Id" />
                    <button class="btn btn-danger btn-lg btn-block delete-button" data-id="@orderProduct.Id">Cancel Order</button>
                    </form>
                </td>
                </tr>
            
            
        }
    </tbody>
</table>
</div>
}



@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+ZCvCkK3uLrW+8v7Fxkew+8dggbmGFIYB6z4bcu" crossorigin="anonymous" defer></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" integrity="sha384-Jn8fzpOj/6+3ovVabw5o9KozIvJF+P5B8PZH8LvguN4JjRZ4WoaXl2slKfL3PW6D" crossorigin="anonymous" defer></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $('.table').DataTable({
                "pageLength": 5,
                "responsive": true
            });
        });
    </script>

 }

Zoro.Web/Areas/Customer/Views/UserOrders/UserOrderHistory.cshtml
@using Zoro.Domain.ViewModel
@model List<CompletedOrderVM>

@{
    int count = 0;
}
<center><h3>Order History</h3></center>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            @if (Model == null || !Model.Any())
            {
                <p>No completed orders found.</p>
            }
            else
            {
                <div class="table-responsive">
                    <table class="table table-bordered table-striped table-responsive-md text-xxl-center text-center">
                        <thead>
                            <tr>
                                <th>S.no</th>
                                <th>Order Date & Time</th>
                                <th>Order ID</th>
                                <th>User Name</th>
                                <th>Product Name</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                <th>Total Price</th>
                                <th>Order Status</th>
                                <th>Phone Number</th>
                                <th>Order Completed Date & Time</th>
                                <th>Image</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var order in Model)
                            {
                                <tr>
                                    <td>@(++count)</td>
                                    <td>@order.CreateOn</td>
                                    <td>@order.OrderId</td>
                                    <td>@order.UserName</td>
                                    <td>@order.ProductName</td>
                                    <td>@order.Quantity</td>
                                    <td>@order.Price.ToString("C")</td>
                                    <td>@order.TotalPrice.ToString("C")</td>
                                    <td><button class="btn btn-success btn-sm">@order.OrderStatus.ToString()</button></td>
                                    <td>@order.PhoneNumber</td>
                                    <td>@order.ModifiedOn</td>
                                    <td><img src="@order.Image" class="img-fluid" style="max-width: 100px; max-height: 100px;"></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+ZCvCkK3uLrW+8v7Fxkew+8dggbmGFIYB6z4bcu" crossorigin="anonymous" defer></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" integrity="sha384-Jn8fzpOj/6+3ovVabw5o9KozIvJF+P5B8PZH8LvguN4JjRZ4WoaXl2slKfL3PW6D" crossorigin="anonymous" defer></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $('.table').DataTable({
                "pageLength": 5,
                "responsive": true
            });
        });
    </script>
}