Zoro.Web/Areas/Admin/Controllers/VechicleTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Microsoft.EntityFrameworkCore;
using System.Drawing;
using System.Reflection.Metadata;
using System.Security.AccessControl;
using Zoro.Application.ApplicationConstants;
using Zoro.Application.Contracts.Persistence;
using Zoro.Domain.Models;
using Zoro.Infrastructure.Comman;
using Zoro.Infrastructure.Migrations;
using VechicleTypes = Zoro.Domain.Models.VechicleTypes;


namespace Zoro.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = CustomRole.MasterAdmin + "," + CustomRole.Admin)]
    public class VechicleTypesController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;

        private readonly IWebHostEnvironment _webhostenvironment;

        public VechicleTypesController(IUnitOfWork UnitOfWork, IWebHostEnvironment Webhostenvironment)
        {
            _unitOfWork = UnitOfWork;
            _webhostenvironment = Webhostenvironment;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            List<VechicleTypes> vechicleTypes = await _unitOfWork.vehicleTypes.GetAllAsync();


            return View(vechicleTypes);
        }

        [HttpGet]
        public IActionResult Create()
        {



            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(VechicleTypes vechicleTypes)
        {
           

            if (ModelState.IsValid)
            {
                await _unitOfWork.vehicleTypes.Create(vechicleTypes);
                await _unitOfWork.SaveAsync();

                TempData["Created"] = CommanMessage.RecordCreated;


                return RedirectToAction(nameof(Index));
            }


            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Detail(Guid id)
        {
            VechicleTypes vechicleTypes = await _unitOfWork.vehicleTypes.GeTByIDAsync(id);

            return View(vechicleTypes);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            VechicleTypes vechicleTypes = await _unitOfWork.vehicleTypes.GeTByIDAsync(id);

            return View(vechicleTypes);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(VechicleTypes vechicleTypes)
        {
           

            if (ModelState.IsValid)
            {



                await _unitOfWork.vehicleTypes.Update(vechicleTypes);
                await _unitOfWork.SaveAsync();

                TempData["Updated"] = CommanMessage.RecordUpdated;
                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            VechicleTypes vechicleTypes = await _unitOfWork.vehicleTypes.GeTByIDAsync(id);

            return View(vechicleTypes);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(VechicleTypes vechicleTypes)
        {
            

            await _unitOfWork.vehicleTypes.Delete(vechicleTypes);
            await _unitOfWork.SaveAsync();

            TempData["Deleted"] = CommanMessage.RecordDeleted;
            return RedirectToAction(nameof(Index));
        }

    }
}

Zoro.Web/Areas/Admin/Views/VechicleTypes/Create.cshtml
@model VechicleTypes
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase">Create CycleTypes</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">
                
                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name"></span>
                </div>

                
                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Index" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-success">Create</button>
                </div>


            </form>


        </div>

    </div>
</div>
@section scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Zoro.Web/Areas/Admin/Views/VechicleTypes/Delete.cshtml
@model VechicleTypes

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase">Delete Brand</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">
                <input asp-for="@Model.Id" hidden />
           

                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" disabled />

                </div>

                




                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Index" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>


            </form>


        </div>

       

    </div>
</div>

Zoro.Web/Areas/Admin/Views/VechicleTypes/Detail.cshtml
@model VechicleTypes
<div class="container">
    <div class="Card">
        <div class="card-header text-center text-uppercase">
            <h2>cycleType Details</h2>
        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-8">


                    <div class="row">

                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Id</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text ">@Model.Id</p>
                        </div>

                    </div>

                    <div class="row">

                        <div class="col-md-4">
                            <p class="card-text text-uppercase"><strong>Name</strong></p>
                        </div>
                        <div class="col-md-8">
                            <p class="card-text ">@Model.Name</p>
                        </div>

                    </div>


                   


                </div>


                

            </div>
            <hr />
            <div class="row">
                <div class="col-md-12 text-center">
                    <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Index" class="btn btn-warning">Back</a>
                </div>
            </div>


        </div>
    </div>
</div>

Zoro.Web/Areas/Admin/Views/VechicleTypes/Edit.cshtml
@model VechicleTypes
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="text-uppercase">Edit VechicleTypes </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 border-1 border">
            <form method="post" enctype="multipart/form-data">

                <div class="mb-3">
                    <label asp-for="@Model.Name" class="form-label"></label>
                    <input asp-for="@Model.Name" class="form-control" />
                    <span asp-validation-for="@Model.Name" class="text-danger"></span>
                </div>

                

                


                <div class="mb-3">
                    <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Index" class="btn btn-warning">Back</a>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>


            </form>


        </div>

       

    </div>
</div>
@section scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Zoro.Web/Areas/Admin/Views/VechicleTypes/Index.cshtml
@model List<VechicleTypes>

@{
    int count = 0;
}
<div class="container">
       <div class="row mb-4"> 
           <div class="col-md-6 text-uppercase">
               <h3>
                 Vechicle types
               </h3>
           </div>

        <div class="col-md-6 text-end">
            <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Create" class="btn btn-primary"><i class="bi bi-patch-plus-fill"></i>Create</a>
    </div>


       </div>

   </div>

   <hr />

<div class="table-responsive">
  <table class="table table-bordered table-stripped" id="table">
    <thead>
        <tr>
                <th style="text-align: center;">S.no</th>
                <th style="text-align: center;">Name</th>               
                <th style="text-align: center;">Action</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var Item in Model)
            {
                <tr>
                    <td style="text-align: center;">@(++count)</td>
                    <td style="text-align: center;">@Item.Name</td>
                   
                    <td class="d-flex align-item-center justify-content-center">
                    <div class="w-75 btn-group" role="group">
                            <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Detail" asp-route-id="@Item.Id" class="btn btn-info"
                               data-toggle="tooltip" data-placement-top title="Detail"><i class="bi bi-info-circle"></i></a>

                            <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Edit" asp-route-id="@Item.Id" class="btn btn-warning"
                               data-toggle="tooltip" data-placement-top title="Edit"><i class="bi bi-pencil-square"></i></a>

                            <a asp-area="Admin" asp-controller="VechicleTypes" asp-action="Delete" asp-route-id="@Item.Id" class="btn btn-danger"
                               data-toggle="tooltip" data-placement-top title="Delete"><i class="bi bi-shield-fill-x"></i></a>
                    </div>
                    </td>
                </tr>
                

                
            }
     </tbody>

    </table>

  </div>


@section Scripts
{
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5+ZCvCkK3uLrW+8v7Fxkew+8dggbmGFIYB6z4bcu" crossorigin="anonymous" defer></script>
    <script src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js" integrity="sha384-Jn8fzpOj/6+3ovVabw5o9KozIvJF+P5B8PZH8LvguN4JjRZ4WoaXl2slKfL3PW6D" crossorigin="anonymous" defer></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            $('.table').DataTable({
                "pageLength": 5,
                "responsive": true
            });
        });
    </script>
}